forgot to fmt; bugs fixed, but see desc
compiler is not cooperating. I'm getting error messages without line numbers, which are extremely non-informative. 6 of them are just "error[E0308]: mismatched types", with no extra info.